### ISSUE TITLE
Board deletion failure on live instance

### ISSUE THREAD

**Issue by ghost** [0-chan-ru/tetuca#9]
The error **500 pq: INSERT has more expressions than target columns** appears when trying to delete a board. It happens on both newly made boards and boards that were alive before the last PR was merged. I can't reproduce it on a local instance regardless of board settings, build environment (arch vs ubuntu LTS) or whether the DB is cleanly setup to v105 with the new PR or migrated from v103 to v105 with the current master. All other board moderator options seem to work.

If you don't have local changes to the DB the only things I can suggest trying are doing truncate table on last_solved_captchas, bans and mod_log and checking if the forcedlive column was not set up correctly in the boards table.

**Comment by nekto-nekto** [comment]
Sorry. Fixed.

**Comment by nekto-nekto** [comment]
Not fixed?
